---
- name: בדיקת העתקת קובץ משיתוף רשת עם לוגים
  hosts: all
  gather_facts: false

  vars:
    share_path: '\\132.72.48.201\installations'
    product_folder: 'Microsoft Office LTSC 2024'
    dest_folder: 'C:\Office2024'
    setup_file: 'setup.exe'

  tasks:

    - name: יצירת תיקיית יעד לבדיקה
      win_file:
        path: "{{ dest_folder }}"
        state: directory

    - name: ניסיון העתקת הקובץ עם net use + copy (כולל echo)
      win_shell: |
        echo === התחלת בדיקה ===
        net use {{ share_path }} /user:auth\{{ ansible_user }} "{{ ansible_password }}"
        echo === מיפוי הסתיים, מתחיל העתקה ===
        copy "{{ share_path }}\{{ product_folder }}\{{ setup_file }}" "{{ dest_folder }}\test_copy.exe"
        echo === סיום העתקה ===
      args:
        executable: cmd
      register: copy_debug
      ignore_errors: true

    - name: הצגת הפלט של פקודת העתקה
      debug:
        var: copy_debug.stdout_lines

    - name: בדיקה אם הקובץ הועתק
      win_stat:
        path: "{{ dest_folder }}\\test_copy.exe"
      register: test_file_status

    - name: סיכום בדיקת ההעתקה
      debug:
        msg: >
          {% if test_file_status.stat.exists %}
          ✔ הקובץ test_copy.exe הועתק בהצלחה
          {% else %}
          ❌ הקובץ לא הועתק. בדוק את נתיב הקובץ, הרשאות, ו־net use.
          {% endif %}
