---
- name: בדיקת חיבור AWX לתחנה והאם יש גישה לשיתוף הרשת
  hosts: all
  gather_facts: false

  vars:
    share_path: '\\132.72.48.201\installations'
    product_folder: 'Microsoft Office LTSC 2024'
    dest_folder: 'C:\Office2024'
    test_file: 'setup.exe'

  tasks:

    - name: הצגת שם המשתמש ש־AWX מריץ איתו את הפקודות
      win_command: whoami
      register: whoami_result

    - name: פלט whoami
      debug:
        msg: "AWX מריץ כ: {{ whoami_result.stdout }}"

    - name: יצירת תיקיית יעד לבדיקה
      win_file:
        path: "{{ dest_folder }}"
        state: directory

    - name: ניסיון מיפוי שיתוף והעתקת קובץ בדיקה
      win_shell: |
        net use {{ share_path }} /user:auth\{{ ansible_user }} "{{ ansible_password }}"
        if %ERRORLEVEL%==0 (
          copy "{{ share_path }}\{{ product_folder }}\{{ test_file }}" "{{ dest_folder }}\test_copy.exe"
        ) else (
          echo ❌ net use נכשל
          exit /b 1
        )
      args:
        executable: cmd
      register: copy_test
      ignore_errors: true
      no_log: false  # אל תפעיל כאן no_log כדי שנראה פלט

    - name: הצגת תוצאת העתקה
      debug:
        var: copy_test.stdout

    - name: בדיקה אם קובץ הבדיקה אכן הועתק
      win_stat:
        path: "{{ dest_folder }}\\test_copy.exe"
      register: test_file_status

    - name: סיכום
      debug:
        msg: >
          {% if test_file_status.stat.exists %}
          ✔ הצלחה! AWX הצליח למפות את השיתוף ולהעתיק את הקובץ.
          {% else %}
          ❌ נכשל להעתיק את הקובץ. ייתכן שזו בעיית הרשאות, נתיב או סביבת הרצה.
          {% endif %}

