---
- name: התקנת Office 2024 מהתקן רשת
  hosts: all
  gather_facts: false

  vars:
    share_path: '\\132.72.48.201\installations'
    product_folder: 'Microsoft Office LTSC 2024'
    dest_folder: 'C:\Office2024'
    setup_file: 'setup.exe'
    config_file: 'Office2024.xml'

  tasks:

    - name: יצירת תיקיית יעד להתקנה
      win_file:
        path: "{{ dest_folder }}"
        state: directory

    - name: העתקת setup.exe מהשיתוף
      win_shell: |
        net use {{ share_path }} /user:auth\{{ ansible_user }} "{{ ansible_password }}"
        if %ERRORLEVEL%==0 (
          copy "{{ share_path }}\{{ product_folder }}\{{ setup_file }}" "{{ dest_folder }}\{{ setup_file }}"
        ) else (
          exit /b 1
        )
      args:
        executable: cmd
      register: copy_setup_result
      no_log: true

    - name: העתקת Office2024.xml מהשיתוף
      win_shell: |
        net use {{ share_path }} /user:auth\{{ ansible_user }} "{{ ansible_password }}"
        if %ERRORLEVEL%==0 (
          copy "{{ share_path }}\{{ product_folder }}\{{ config_file }}" "{{ dest_folder }}\{{ config_file }}"
        ) else (
          exit /b 1
        )
      args:
        executable: cmd
      register: copy_xml_result
      no_log: true

    - name: בדיקה אם setup.exe קיים
      win_stat:
        path: "{{ dest_folder }}\\{{ setup_file }}"
      register: setup_exists

    - name: בדיקה אם Office2024.xml קיים
      win_stat:
        path: "{{ dest_folder }}\\{{ config_file }}"
      register: config_exists

    - name: הרצת setup.exe עם קובץ ההגדרות
      win_command: "{{ dest_folder }}\\{{ setup_file }} /configure {{ dest_folder }}\\{{ config_file }}"
      args:
        chdir: "{{ dest_folder }}"
      when: setup_exists.stat.exists and config_exists.stat.exists
      register: install_result

    - name: תצוגת הצלחה
      debug:
        msg: "✔ ההתקנה בוצעה בתחנה {{ inventory_hostname }}"
      when: install_result is defined and install_result.rc == 0

    - name: תצוגת כישלון – קבצים חסרים
      debug:
        msg: "❌ הקבצים לא נמצאו בתחנה {{ inventory_hostname }} – לא בוצעה התקנה"
      when: not (setup_exists.stat.exists and config_exists.stat.exists)
