---
- name: בדיקת העתקת קובץ משיתוף רשת עם לוגים מורחבים
  hosts: all
  gather_facts: false

  vars:
    share_path: '\\132.72.48.201\installations'
    product_folder: 'Microsoft Office LTSC 2024'
    dest_folder: 'C:\Office2024'
    setup_file: 'setup.exe'

  tasks:

    - name: יצירת תיקיית יעד לבדיקה
      win_file:
        path: "{{ dest_folder }}"
        state: directory

    - name: ניסיון העתקת קובץ מהשיתוף עם לוגים מפורטים
      win_shell: |
        echo === התחלת בדיקה ===
        net use {{ share_path }} /user:auth\{{ ansible_user }} "{{ ansible_password }}" || echo ❌ net use נכשל עם קוד %ERRORLEVEL%
        echo ERRORLEVEL אחרי net use: %ERRORLEVEL%
        if %ERRORLEVEL%==0 (
          echo === מיפוי הצליח ===
          copy "{{ share_path }}\{{ product_folder }}\{{ setup_file }}" "{{ dest_folder }}\test_copy.exe" || echo ❌ copy נכשל עם קוד %ERRORLEVEL%
          echo קובץ הועתק בהצלחה
        ) else (
          echo ❌ net use נכשל. יציאה
          exit /b 1
        )
      args:
        executable: cmd
      register: copy_debug
      ignore_errors: true

    - name: הצגת הפלט המלא מהפקודה
      debug:
        var: copy_debug.stdout_lines

    - name: בדיקת קיום קובץ ההעתקה
      win_stat:
        path: "{{ dest_folder }}\\test_copy.exe"
      register: test_file_status

    - name: סיכום
      debug:
        msg: >
          {% if test_file_status.stat.exists %}
          ✔ הצלחה: הקובץ test_copy.exe הועתק בהצלחה ל-{{ inventory_hostname }}
          {% else %}
          ❌ כישלון: הקובץ לא הועתק ל-{{ inventory_hostname }}. יש לבדוק את השיתוף או ההרשאות.
          {% endif %}
