---
- name: Install Office from SMB using AWX Credential
  hosts: all
  gather_facts: no
  tasks:

    - name: Ensure install folder exists
      win_file:
        path: C:\Office2024
        state: directory

    - name: Connect to SMB share
      win_command: >
        net use \\132.72.48.201\installations /user:{{ ansible_user }} "{{ ansible_password }}"

    - name: Copy setup.exe
      win_command: >
        cmd /c copy "\\132.72.48.201\installations\Microsoft Office LTSC 2024\setup.exe" "C:\Office2024\setup.exe"

    - name: Copy configuration.xml
      win_command: >
        cmd /c copy "\\132.72.48.201\installations\Microsoft Office LTSC 2024\Office2024.xml" "C:\Office2024\Office2024.xml"

    - name: Run Office installer
      win_command: >
        C:\Office2024\setup.exe /configure C:\Office2024\Office2024.xml
