---
- name: Install Office 2024 from network share
  hosts: all
  gather_facts: no
  tasks:

    - name: Create installation directory
      win_file:
        path: C:\Office2024
        state: directory

    - name: Copy Office setup.exe from network share
      win_command: |
        copy "\\132.72.48.201\installations\Microsoft Office LTSC 2024\setup.exe" "C:\Office2024\setup.exe"

    - name: Copy configuration.xml from network share
      win_command: |
        copy "\\132.72.48.201\installations\Microsoft Office LTSC 2024\Office2024.xml" "C:\Office2024\Office2024.xml"

    - name: Run Office installer with config
      win_command: C:\Office2024\setup.exe /configure C:\Office2024\Office2024.xml
      args:
        chdir: C:\Office2024
      register: office_result

    - name: Print install result
      debug:
        var: office_result.stdout

